<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Working with iNaturalist data – iNaturalist CNC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
// https://stackoverflow.com/questions/76119872/quarto-website-make-template-for-javascript-button-show-answer

  function addAnswerWithButton(answerClass, buttonText, answerText) {

    const divElement = document.querySelector(`.${answerClass}`);
    const randomId = "answer-" + Math.floor(Math.random() * 1000000);

    // Create the new button element
    const buttonElement = document.createElement("button");
    buttonElement.className = "btn btn-primary show-answer";
    buttonElement.textContent = 'Show solution';
    buttonElement.onclick = function() {
      showAnswer(randomId);
    };

    // Create the new answer element
    const answerElement = document.createElement("div");
    answerElement.id = randomId;
    answerElement.style.display = "none";
    answerElement.innerHTML = answerText;

    // Replace the div element with the new button and answer elements
    divElement.parentNode.replaceChild(buttonElement, divElement);
    buttonElement.insertAdjacentElement("afterend", answerElement);
  }

  function showAnswer(answerId) {
    var answer = document.getElementById(answerId);
    if (answer.style.display === "none") {
      answer.style.display = "block";
    } else {
      answer.style.display = "none";
    }
  }

  function addAnswerButton() {
    var answers = document.querySelectorAll(".answer")
    answers.forEach(e => {
      addAnswerWithButton("answer", " Show solution", e.innerHTML);
    });
  }

  window.document.addEventListener("DOMContentLoaded", function (event) {
    addAnswerButton();
  });
</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">iNaturalist CNC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lessons/working-with-data.html">Working with iNaturalist data</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/intro-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/intro-r-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to R and RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/intro-science-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Science and Coding concepts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/working-with-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Working with iNaturalist data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/creating-maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating maps</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/creating-charts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating charts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/other_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using to other datasets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lessons/next-steps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Next steps</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#importing-inaturalist-data" id="toc-importing-inaturalist-data" class="nav-link active" data-scroll-target="#importing-inaturalist-data">Importing iNaturalist data</a>
  <ul class="collapse">
  <li><a href="#reading-a-file" id="toc-reading-a-file" class="nav-link" data-scroll-target="#reading-a-file">Reading a file</a></li>
  </ul></li>
  <li><a href="#the-data.frame" id="toc-the-data.frame" class="nav-link" data-scroll-target="#the-data.frame">The data.frame</a></li>
  <li><a href="#manipulating-data" id="toc-manipulating-data" class="nav-link" data-scroll-target="#manipulating-data">Manipulating data</a>
  <ul class="collapse">
  <li><a href="#select" id="toc-select" class="nav-link" data-scroll-target="#select">select()</a></li>
  <li><a href="#filter" id="toc-filter" class="nav-link" data-scroll-target="#filter">filter()</a></li>
  <li><a href="#the-pipe" id="toc-the-pipe" class="nav-link" data-scroll-target="#the-pipe">The pipe: %&gt;%</a></li>
  </ul></li>
  <li><a href="#errors-in-code" id="toc-errors-in-code" class="nav-link" data-scroll-target="#errors-in-code">Errors in code</a></li>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#and-operator" id="toc-and-operator" class="nav-link" data-scroll-target="#and-operator">and operator: &amp;</a></li>
  <li><a href="#or-operator" id="toc-or-operator" class="nav-link" data-scroll-target="#or-operator">or operator: |</a></li>
  <li><a href="#in-c" id="toc-in-c" class="nav-link" data-scroll-target="#in-c">%in% c()</a></li>
  <li><a href="#and-versus-or" id="toc-and-versus-or" class="nav-link" data-scroll-target="#and-versus-or">&amp; (and) versus | (or)</a></li>
  <li><a href="#more-complex-queries" id="toc-more-complex-queries" class="nav-link" data-scroll-target="#more-complex-queries">More complex queries</a></li>
  <li><a href="#higher-taxonomy" id="toc-higher-taxonomy" class="nav-link" data-scroll-target="#higher-taxonomy">Higher taxonomy</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#add-new-columns-with-mutate" id="toc-add-new-columns-with-mutate" class="nav-link" data-scroll-target="#add-new-columns-with-mutate">Add new columns with mutate()</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  <li><a href="#count-the-number-of-rows-with-count" id="toc-count-the-number-of-rows-with-count" class="nav-link" data-scroll-target="#count-the-number-of-rows-with-count">Count the number of rows with count()</a></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a></li>
  <li><a href="#save-data" id="toc-save-data" class="nav-link" data-scroll-target="#save-data">Save data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Working with iNaturalist data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="summary">
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<ul>
<li>How do you work with iNaturalist CSV data in R?</li>
</ul>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<ul>
<li>Import CSV data into R.</li>
<li>Select rows and columns of data.frames.</li>
<li>Use pipes to link steps together into pipelines.</li>
<li>Create new data.frame columns using existing columns.</li>
<li>Export data to a CSV file.</li>
</ul>
</section>
</div>
<section id="importing-inaturalist-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-inaturalist-data">Importing iNaturalist data</h2>
<p>A CSV of iNaturalist observations for City Nature Challenge Los Angeles from 2015 to 2024 is located at “data/cleaned/cnc-los-angeles-observations.csv”. We are going to read that CSV using R.</p>
<section id="reading-a-file" class="level3">
<h3 class="anchored" data-anchor-id="reading-a-file">Reading a file</h3>
<p>In order to analyze the iNaturalist csv, we need to load <strong>readr</strong>, <strong>lubridate</strong> and <strong>dplyr</strong> packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) <span class="co"># read and write tabular data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># manipulate data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate) <span class="co"># manipulate dates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will use the <code>read_csv()</code> function from <strong>readr</strong> package to read the iNaturalist CSV. We will pass in a relative path to the CSV file as an argument for <code>read_csv()</code>.</p>
<p><code>read_csv()</code> will return the content of the file. In order for us access the data later on, we need to assign the content to an object called <code>inat_data</code>. Objects are displayed in the <strong>Environment</strong> panel. Double click on <code>inat_data</code> in <strong>Environment</strong> to see all the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'data/cleaned/cnc-los-angeles-observations.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Typing out paths can be error prone, so we can utilize a keyboard shortcut. Inside the parentheses of <code>read_csv()</code>, type out a pair of quotes and put your cursor between them. Then hit <kbd>Tab</kbd>. A small menu showing your folders and files should show up. You can use the <kbd>↑</kbd> and <kbd>↓</kbd> keys to move through the options, or start typing to narrow them down. You can hit <kbd>Enter</kbd> to select a file or folder, and hit <kbd>Tab</kbd> again to continue building the file path. This might take a bit of getting used to, but once you get the hang of it, it will speed up writing file paths and reduce the number of mistakes you make.</p>
</div>
</div>
<p>To learn more about a function, you can type a <code>?</code> in front of the name of the function, which will bring up the official documentation for that function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>?read_csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Function documentation is written by the authors of the functions, so they can vary pretty widely in their style and readability. The first section, <strong>Description</strong>, gives you a concise description of what the function does, but it may not always be enough. The <strong>Arguments</strong> section defines all the arguments for the function and is usually worth reading thoroughly. Finally, the <strong>Examples</strong> section at the end will often have some helpful examples that you can run to get a sense of what the function is doing.</p>
</section>
</section>
<section id="the-data.frame" class="level2">
<h2 class="anchored" data-anchor-id="the-data.frame">The data.frame</h2>
<p>read_csv returns a <strong>data.frame</strong>. A <strong>data.frame</strong> is the most common way that R represents tabular data (data with rows and columns).</p>
<p>We can view the first few rows with the <code>head()</code> function from R, and the last few rows with the <code>tail()</code> function from R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(inat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 37
       id observed_on time_observed_at   user_id user_login user_name created_at
    &lt;dbl&gt; &lt;date&gt;      &lt;chr&gt;                &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     
1 2931940 2016-04-14  2016-04-14 19:25:…  151043 msmorales  Michael … 2016-04-1…
2 2934641 2016-04-14  2016-04-14 19:02:…   10814 smartrf    Richard … 2016-04-1…
3 2934961 2016-04-14  2016-04-14 19:15:…   80445 cdegroof   Chris De… 2016-04-1…
4 2934980 2016-04-14  2016-04-14 19:18:…   80445 cdegroof   Chris De… 2016-04-1…
5 2934994 2016-04-14  2016-04-14 19:19:…   80445 cdegroof   Chris De… 2016-04-1…
6 2935037 2016-04-14  2016-04-14 19:36:…  121033 ttempel    &lt;NA&gt;      2016-04-1…
# ℹ 30 more variables: updated_at &lt;chr&gt;, quality_grade &lt;chr&gt;, license &lt;chr&gt;,
#   url &lt;chr&gt;, image_url &lt;chr&gt;, sound_url &lt;chr&gt;, tag_list &lt;chr&gt;,
#   description &lt;chr&gt;, captive_cultivated &lt;lgl&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, positional_accuracy &lt;dbl&gt;,
#   public_positional_accuracy &lt;dbl&gt;, geoprivacy &lt;chr&gt;, taxon_geoprivacy &lt;chr&gt;,
#   coordinates_obscured &lt;lgl&gt;, scientific_name &lt;chr&gt;, common_name &lt;chr&gt;,
#   iconic_taxon_name &lt;chr&gt;, taxon_id &lt;dbl&gt;, taxon_kingdom_name &lt;chr&gt;, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(inat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 37
         id observed_on time_observed_at user_id user_login user_name created_at
      &lt;dbl&gt; &lt;date&gt;      &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     
1 254128969 2024-04-28  2024-04-28 17:1… 2834615 thannavic… Thanna V… 2024-12-0…
2 255041807 2024-04-26  2024-04-26 23:3… 5347031 epiphyte78 &lt;NA&gt;      2024-12-1…
3 255041881 2024-04-26  2024-04-26 22:1… 5347031 epiphyte78 &lt;NA&gt;      2024-12-1…
4 255041985 2024-04-26  2024-04-26 22:1… 5347031 epiphyte78 &lt;NA&gt;      2024-12-1…
5 255042063 2024-04-26  2024-04-26 20:4… 5347031 epiphyte78 &lt;NA&gt;      2024-12-1…
6 255042124 2024-04-26  2024-04-26 19:1… 5347031 epiphyte78 &lt;NA&gt;      2024-12-1…
# ℹ 30 more variables: updated_at &lt;chr&gt;, quality_grade &lt;chr&gt;, license &lt;chr&gt;,
#   url &lt;chr&gt;, image_url &lt;chr&gt;, sound_url &lt;chr&gt;, tag_list &lt;chr&gt;,
#   description &lt;chr&gt;, captive_cultivated &lt;lgl&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, positional_accuracy &lt;dbl&gt;,
#   public_positional_accuracy &lt;dbl&gt;, geoprivacy &lt;chr&gt;, taxon_geoprivacy &lt;chr&gt;,
#   coordinates_obscured &lt;lgl&gt;, scientific_name &lt;chr&gt;, common_name &lt;chr&gt;,
#   iconic_taxon_name &lt;chr&gt;, taxon_id &lt;dbl&gt;, taxon_kingdom_name &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>Use <code>glimpse()</code> from <strong>dplyr</strong> to see a information about a data frame. Number of rows and columns. For each column, we see the name, data type (<strong>dbl</strong> for number, <strong>chr</strong> for character, <strong>lgl</strong> for logical (true, false), <strong>date</strong> for date), and the first few values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(inat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 191,638
Columns: 37
$ id                         &lt;dbl&gt; 2931940, 2934641, 2934961, 2934980, 2934994…
$ observed_on                &lt;date&gt; 2016-04-14, 2016-04-14, 2016-04-14, 2016-0…
$ time_observed_at           &lt;chr&gt; "2016-04-14 19:25:00 UTC", "2016-04-14 19:0…
$ user_id                    &lt;dbl&gt; 151043, 10814, 80445, 80445, 80445, 121033,…
$ user_login                 &lt;chr&gt; "msmorales", "smartrf", "cdegroof", "cdegro…
$ user_name                  &lt;chr&gt; "Michael Morales", "Richard Smart (he, him)…
$ created_at                 &lt;chr&gt; "2016-04-14 07:28:36 UTC", "2016-04-14 19:0…
$ updated_at                 &lt;chr&gt; "2021-12-26 06:58:04 UTC", "2018-05-28 02:0…
$ quality_grade              &lt;chr&gt; "research", "needs_id", "research", "resear…
$ license                    &lt;chr&gt; "CC-BY", "CC-BY-NC", NA, NA, NA, "CC-BY-NC"…
$ url                        &lt;chr&gt; "http://www.inaturalist.org/observations/29…
$ image_url                  &lt;chr&gt; "https://inaturalist-open-data.s3.amazonaws…
$ sound_url                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ tag_list                   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ description                &lt;chr&gt; "Spotted on a the wall of a planter, while …
$ captive_cultivated         &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ latitude                   &lt;dbl&gt; 34.05829, 34.01742, 34.13020, 34.13143, 34.…
$ longitude                  &lt;dbl&gt; -117.8219, -118.2892, -118.8226, -118.8215,…
$ positional_accuracy        &lt;dbl&gt; 4, 5, NA, NA, NA, NA, 17, 55, 55, 55, NA, 5…
$ public_positional_accuracy &lt;dbl&gt; 4, 5, NA, NA, NA, NA, 17, 55, 55, 55, NA, 5…
$ geoprivacy                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ taxon_geoprivacy           &lt;chr&gt; NA, NA, NA, "open", "open", NA, "open", NA,…
$ coordinates_obscured       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ scientific_name            &lt;chr&gt; "Cornu aspersum", "Oestroidea", "Arphia ram…
$ common_name                &lt;chr&gt; "Garden Snail", "Bot Flies, Blow Flies, and…
$ iconic_taxon_name          &lt;chr&gt; "Mollusca", "Insecta", "Insecta", "Reptilia…
$ taxon_id                   &lt;dbl&gt; 480298, 356157, 54247, 36100, 36204, 69731,…
$ taxon_kingdom_name         &lt;chr&gt; "Animalia", "Animalia", "Animalia", "Animal…
$ taxon_phylum_name          &lt;chr&gt; "Mollusca", "Arthropoda", "Arthropoda", "Ch…
$ taxon_class_name           &lt;chr&gt; "Gastropoda", "Insecta", "Insecta", "Reptil…
$ taxon_order_name           &lt;chr&gt; "Stylommatophora", "Diptera", "Orthoptera",…
$ taxon_family_name          &lt;chr&gt; "Helicidae", NA, "Acrididae", "Phrynosomati…
$ taxon_genus_name           &lt;chr&gt; "Cornu", NA, "Arphia", "Uta", "Sceloporus",…
$ taxon_species_name         &lt;chr&gt; "Cornu aspersum", NA, "Arphia ramona", "Uta…
$ taxon_subspecies_name      &lt;chr&gt; NA, NA, NA, "Uta stansburiana elegans", NA,…
$ threatened                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ establishment_means        &lt;chr&gt; "introduced", NA, "native", "native", "nati…</code></pre>
</div>
</div>
<p>You can also use <code>names()</code> from R to see the fields in the data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(inat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "id"                         "observed_on"               
 [3] "time_observed_at"           "user_id"                   
 [5] "user_login"                 "user_name"                 
 [7] "created_at"                 "updated_at"                
 [9] "quality_grade"              "license"                   
[11] "url"                        "image_url"                 
[13] "sound_url"                  "tag_list"                  
[15] "description"                "captive_cultivated"        
[17] "latitude"                   "longitude"                 
[19] "positional_accuracy"        "public_positional_accuracy"
[21] "geoprivacy"                 "taxon_geoprivacy"          
[23] "coordinates_obscured"       "scientific_name"           
[25] "common_name"                "iconic_taxon_name"         
[27] "taxon_id"                   "taxon_kingdom_name"        
[29] "taxon_phylum_name"          "taxon_class_name"          
[31] "taxon_order_name"           "taxon_family_name"         
[33] "taxon_genus_name"           "taxon_species_name"        
[35] "taxon_subspecies_name"      "threatened"                
[37] "establishment_means"       </code></pre>
</div>
</div>
</section>
<section id="manipulating-data" class="level2">
<h2 class="anchored" data-anchor-id="manipulating-data">Manipulating data</h2>
<p>One of the most important skills for working with data in R is the ability to manipulate, modify, and reshape data. The <strong>dplyr</strong> package provide a series of powerful functions for many common data manipulation tasks.</p>
<section id="select" class="level3">
<h3 class="anchored" data-anchor-id="select">select()</h3>
<p><code>select()</code> picks certain columns of a data.frame. To use the <code>select()</code> function, the first argument is the name of the data.frame, and the rest of the arguments are unquoted names of the columns you want.</p>
<p>We want four columns: <code>user_login</code>, <code>common_name</code>, <code>scientific_name</code>, <code>observed_on</code>. The columns are arranged in the order we specified inside <code>select()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(inat_data, user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 191,638 × 4
   user_login    common_name                         scientific_name observed_on
   &lt;chr&gt;         &lt;chr&gt;                               &lt;chr&gt;           &lt;date&gt;     
 1 msmorales     Garden Snail                        Cornu aspersum  2016-04-14 
 2 smartrf       Bot Flies, Blow Flies, and Allies   Oestroidea      2016-04-14 
 3 cdegroof      California Orange-winged Grasshopp… Arphia ramona   2016-04-14 
 4 cdegroof      Western Side-blotched Lizard        Uta stansburia… 2016-04-14 
 5 cdegroof      Western Fence Lizard                Sceloporus occ… 2016-04-14 
 6 ttempel       &lt;NA&gt;                                Coelocnemis     2016-04-14 
 7 bradrumble    House Sparrow                       Passer domesti… 2016-04-15 
 8 deedeeflower5 Amur Carp                           Cyprinus rubro… 2016-04-14 
 9 deedeeflower5 Red-eared Slider                    Trachemys scri… 2016-04-14 
10 deedeeflower5 Mallard                             Anas platyrhyn… 2016-04-14 
# ℹ 191,628 more rows</code></pre>
</div>
</div>
</section>
<section id="filter" class="level3">
<h3 class="anchored" data-anchor-id="filter">filter()</h3>
<p>The <code>filter()</code> function is used to select rows that meet certain criteria. To get all the rows where the value of <code>common_name</code> is equal to ‘Western Fence Lizard’, we would run the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(inat_data, common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,339 × 37
        id observed_on time_observed_at  user_id user_login user_name created_at
     &lt;dbl&gt; &lt;date&gt;      &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     
 1 2934994 2016-04-14  2016-04-14 19:19…   80445 cdegroof   Chris De… 2016-04-1…
 2 2935263 2016-04-14  &lt;NA&gt;               216108 deedeeflo… &lt;NA&gt;      2016-04-1…
 3 2935420 2016-04-14  &lt;NA&gt;               216108 deedeeflo… &lt;NA&gt;      2016-04-1…
 4 2935748 2016-04-14  2016-04-14 21:01…   80445 cdegroof   Chris De… 2016-04-1…
 5 2935965 2016-04-14  2016-04-14 19:44…  171443 lchroman   &lt;NA&gt;      2016-04-1…
 6 2938607 2016-04-14  2016-04-14 23:33…  146517 maiz       &lt;NA&gt;      2016-04-1…
 7 2940103 2016-04-15  2016-04-15 16:31…   80984 kimssight  Kim Moore 2016-04-1…
 8 2940838 2016-04-15  2016-04-15 17:11…  201119 sarahwenn… &lt;NA&gt;      2016-04-1…
 9 2940848 2016-04-15  2016-04-15 17:17…  201119 sarahwenn… &lt;NA&gt;      2016-04-1…
10 2940855 2016-04-15  2016-04-15 17:42…  201119 sarahwenn… &lt;NA&gt;      2016-04-1…
# ℹ 3,329 more rows
# ℹ 30 more variables: updated_at &lt;chr&gt;, quality_grade &lt;chr&gt;, license &lt;chr&gt;,
#   url &lt;chr&gt;, image_url &lt;chr&gt;, sound_url &lt;chr&gt;, tag_list &lt;chr&gt;,
#   description &lt;chr&gt;, captive_cultivated &lt;lgl&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, positional_accuracy &lt;dbl&gt;,
#   public_positional_accuracy &lt;dbl&gt;, geoprivacy &lt;chr&gt;, taxon_geoprivacy &lt;chr&gt;,
#   coordinates_obscured &lt;lgl&gt;, scientific_name &lt;chr&gt;, common_name &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>There are over 3000 observations for ‘Western Fence Lizard’.</p>
<p>The <code>==</code> sign means “is equal to”. Take note, there are two equal signs.</p>
<p>There are several other operators we can use: &gt; “greater than”, &gt;= “greater than or equal”, &lt; “less than”, &lt;= “less than or equal”, and != “not equal to”.</p>
</section>
<section id="the-pipe" class="level3">
<h3 class="anchored" data-anchor-id="the-pipe">The pipe: %&gt;%</h3>
<p>What happens if we want to select columns and filter rows?</p>
<p>We use the pipe operator (<code>%&gt;%</code>) to call multiple functions.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can insert <code>%&gt;%</code> by using the keyboard shortcut <kbd>Shift+Cmd+M</kbd> (Mac) or <kbd>Shift+Ctrl+M</kbd> (Windows).</p>
</div>
</div>
<p>Get <code>user_login</code>, <code>common_name</code>, <code>scientific_name</code>, <code>observed_on</code> for all observations where <code>common_name</code> is ‘Western Fence Lizard’. Use filter to select rows, then use select to select columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,339 × 4
   user_login    common_name          scientific_name         observed_on
   &lt;chr&gt;         &lt;chr&gt;                &lt;chr&gt;                   &lt;date&gt;     
 1 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 2 deedeeflower5 Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 3 deedeeflower5 Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 4 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 5 lchroman      Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 6 maiz          Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 7 kimssight     Western Fence Lizard Sceloporus occidentalis 2016-04-15 
 8 sarahwenner   Western Fence Lizard Sceloporus occidentalis 2016-04-15 
 9 sarahwenner   Western Fence Lizard Sceloporus occidentalis 2016-04-15 
10 sarahwenner   Western Fence Lizard Sceloporus occidentalis 2016-04-15 
# ℹ 3,329 more rows</code></pre>
</div>
</div>
<p>Pipe operator take the thing on the lefthand side and insert it as the first argument of the function on the righthand side. By putting each of our functions onto a new line, we can build a nice, readable pipeline. <code>inat_data</code> gets piped into a <code>filter()</code> function, and it comes out modified somewhat. The output from <code>filter()</code> then gets sent into the <code>select()</code> function, where it is further modified. It can also be helpful to think of <code>%&gt;%</code> as meaning “and then”.</p>
<p>If we want to store this final data frame as an object, we use an assignment arrow <code>&lt;-</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>western_fence_lizard_obs <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sometimes the coordinates for iNaturalist observations are obscured. For instance, when the observation involves an endangered species, iNaturalist will automatically obscure the coordinates in order to protect the animal, plant, fungi. Sometimes peopleb choose to obscure their location when they are making observations so that other people will not know their exact location.</p>
<p>To access one column in a data frame, use <code>dataframe$column_name</code>. To get a count of number of values for one column, use <code>table()</code> function from R and pass in one column.</p>
<p>Let’s find out how many observations have obscured locations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(inat_data<span class="sc">$</span>coordinates_obscured)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 FALSE   TRUE 
176942  14696 </code></pre>
</div>
</div>
<p>176K coordinates are ok, 14K are obscured</p>
<p>Let’s get the observations where the coordinates are not obscured.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(coordinates_obscured <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 176,942 × 4
   user_login    common_name                         scientific_name observed_on
   &lt;chr&gt;         &lt;chr&gt;                               &lt;chr&gt;           &lt;date&gt;     
 1 msmorales     Garden Snail                        Cornu aspersum  2016-04-14 
 2 smartrf       Bot Flies, Blow Flies, and Allies   Oestroidea      2016-04-14 
 3 cdegroof      California Orange-winged Grasshopp… Arphia ramona   2016-04-14 
 4 cdegroof      Western Side-blotched Lizard        Uta stansburia… 2016-04-14 
 5 cdegroof      Western Fence Lizard                Sceloporus occ… 2016-04-14 
 6 ttempel       &lt;NA&gt;                                Coelocnemis     2016-04-14 
 7 bradrumble    House Sparrow                       Passer domesti… 2016-04-15 
 8 deedeeflower5 Amur Carp                           Cyprinus rubro… 2016-04-14 
 9 deedeeflower5 Red-eared Slider                    Trachemys scri… 2016-04-14 
10 deedeeflower5 Mallard                             Anas platyrhyn… 2016-04-14 
# ℹ 176,932 more rows</code></pre>
</div>
</div>
<p>iNaturalist gives a quality grade to each observation. When researchers use iNaturalist data, they normally use research grade observations.</p>
<p>To see all the unique values for a column, use <code>unique()</code> function from R and pass in the column name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(inat_data<span class="sc">$</span>quality_grade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "research" "needs_id" "casual"  </code></pre>
</div>
</div>
<p>Let’s get the observations that are research grade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(quality_grade <span class="sc">==</span> <span class="st">'research'</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 107,491 × 4
   user_login    common_name                         scientific_name observed_on
   &lt;chr&gt;         &lt;chr&gt;                               &lt;chr&gt;           &lt;date&gt;     
 1 msmorales     Garden Snail                        Cornu aspersum  2016-04-14 
 2 cdegroof      California Orange-winged Grasshopp… Arphia ramona   2016-04-14 
 3 cdegroof      Western Side-blotched Lizard        Uta stansburia… 2016-04-14 
 4 cdegroof      Western Fence Lizard                Sceloporus occ… 2016-04-14 
 5 deedeeflower5 Red-eared Slider                    Trachemys scri… 2016-04-14 
 6 deedeeflower5 Mallard                             Anas platyrhyn… 2016-04-14 
 7 lchroman      Cactus Wren                         Campylorhynchu… 2016-04-14 
 8 deedeeflower5 Desert Cottontail                   Sylvilagus aud… 2016-04-14 
 9 deedeeflower5 Western Fence Lizard                Sceloporus occ… 2016-04-14 
10 deedeeflower5 Eastern Fox Squirrel                Sciurus niger   2016-04-14 
# ℹ 107,481 more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="errors-in-code" class="level2">
<h2 class="anchored" data-anchor-id="errors-in-code">Errors in code</h2>
<p>We are writing instructions for the computer. If there is a typo, mispelling, pass in wrong arguments into functions, etc, the code will not work and we will see errors. R will display the errors in red. You need to fix the errors in order for the code to work.</p>
<p>typo: we used <code>%&gt;</code>, when it should be <code>%&gt;%</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>inat_data %<span class="sc">&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Misspelled <code>user_logi</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_logi, observed_on, common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>typo: we use <code>=</code>, when it should be <code>==</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="at">user_login =</span> <span class="st">'natureinla'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>typo: extra <code>)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name)<span class="er">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-1" class="level2 exercise">
<h2 class="anchored" data-anchor-id="exercise-1">Exercise 1</h2>
<p>Get all your City Nature Challenge observations.</p>
<ul>
<li>Use <code>select()</code>, <code>filter()</code></li>
<li>The results should have <code>user_login</code> equal to your iNaturalist username</li>
<li>The results should have <code>user_login</code>, <code>observed_on</code>, <code>common_name</code>, <code>scientific_name</code> columns</li>
<li>save the results to <code>my_obs</code></li>
<li>click on <code>my_obs</code> in the Environment tab to see the results</li>
</ul>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>my_obs <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name, scientific_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="and-operator" class="level2">
<h2 class="anchored" data-anchor-id="and-operator">and operator: &amp;</h2>
<p>When we want go get rows that match multiple criteria, we can use the and operator <code>&amp;</code></p>
<p>Let’s get all observations that are research grade and <code>common_name</code> is ‘Western Fence Lizard’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">&amp;</span> quality_grade <span class="sc">==</span> <span class="st">'research'</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on, quality_grade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can check the results to make sure we wrote the query correctly. We can use <code>unique()</code> to check the column values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>quality_grade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "research"</code></pre>
</div>
</div>
<p>Let’s get observations where <code>user_login</code> is ‘natureinla’ and <code>common_name</code> is ‘Western Fence Lizard’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span> <span class="sc">&amp;</span> common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>user_login)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "natureinla"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard"</code></pre>
</div>
</div>
</section>
<section id="or-operator" class="level2">
<h2 class="anchored" data-anchor-id="or-operator">or operator: |</h2>
<p>When we want to get rows that match one or more criteria, we can use the or operator <code>|</code></p>
<p>Let’s get observations where <code>common_name</code> is ‘Western Fence Lizard’ or ‘Western Honey Bee’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'Western Honey Bee'</span> <span class="sc">|</span> common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5399    3</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard" "Western Honey Bee"   </code></pre>
</div>
</div>
</section>
<section id="in-c" class="level2">
<h2 class="anchored" data-anchor-id="in-c">%in% c()</h2>
<p>If you need to examine multiple values for a field, you can use <code>field_name %in% c(value1, value2)</code> instead of <code>|</code> (or).</p>
<p>A vector is how R stores a list of items. <code>c()</code> is a function from R that creates a vector with the passed in agruments. <code>%in%</code> operator from R checks if a vector is contained in another vector.</p>
<p>Let’s rewrite the the code for <code>common_name</code> is ‘Western Fence Lizard’ or ‘Western Honey Bee’ using <code>%in% c()</code>. This codes will find observations where <code>common_names</code> is in the vector: ‘Western Honey Bee’, ‘Western Fence Lizard’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'Western Honey Bee'</span>, <span class="st">'Western Fence Lizard'</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5399    3</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_data<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard" "Western Honey Bee"   </code></pre>
</div>
</div>
</section>
<section id="and-versus-or" class="level2">
<h2 class="anchored" data-anchor-id="and-versus-or">&amp; (and) versus | (or)</h2>
<p>** &amp; (and)** return rows where all conditions are true. This code looks for observations where user_login is ‘natureinla’ and common_name is ‘Western Fence Lizard’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>and_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span> <span class="sc">&amp;</span> common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(and_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79 37</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(and_data<span class="sc">$</span>user_login)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "natureinla"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(and_data<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard"</code></pre>
</div>
</div>
<p>We get 79 rows with 1 user_login and 1 common_name</p>
<p><strong>| (or)</strong> returns rows where any conditions are true. This code looks for observations where user_login is ‘natureinla’ plus observations where common_name is ‘Western Fence Lizard’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>or_data <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span> <span class="sc">|</span> common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(or_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6216   37</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(or_data<span class="sc">$</span>user_login) <span class="sc">%&gt;%</span> length</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1052</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(or_data<span class="sc">$</span>common_name) <span class="sc">%&gt;%</span> length</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1031</code></pre>
</div>
</div>
<p>We get 6,216 rows with 1052 user_login and 1031 common_name</p>
<p>And / Or will return different results. In other words, check the results of your code to make sure your results matches what you intended</p>
</section>
<section id="more-complex-queries" class="level2">
<h2 class="anchored" data-anchor-id="more-complex-queries">More complex queries</h2>
<p>Sometimes we want to use both <code>and</code> <code>or</code> to select the rows. We want observations where user is ‘cdegroof’ or ‘deedeeflower5’, and species is ‘Western Fence Lizard’. You can use multiple filter statememts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>complex_query <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'cdegroof'</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">|</span> user_login <span class="sc">==</span> <span class="st">'deedeeflower5'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'Western Fence Lizard'</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, common_name, scientific_name, observed_on)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>complex_query</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 4
   user_login    common_name          scientific_name         observed_on
   &lt;chr&gt;         &lt;chr&gt;                &lt;chr&gt;                   &lt;date&gt;     
 1 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 2 deedeeflower5 Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 3 deedeeflower5 Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 4 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-14 
 5 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-16 
 6 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-16 
 7 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-16 
 8 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-17 
 9 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-17 
10 cdegroof      Western Fence Lizard Sceloporus occidentalis 2016-04-17 
# ℹ 23 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(complex_query<span class="sc">$</span>common_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Western Fence Lizard"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(complex_query<span class="sc">$</span>user_login)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "cdegroof"      "deedeeflower5"</code></pre>
</div>
</div>
</section>
<section id="higher-taxonomy" class="level2">
<h2 class="anchored" data-anchor-id="higher-taxonomy">Higher taxonomy</h2>
<p>So far we looked at species. Instead of looking at specific species, we can also look for a group of related species.</p>
<p>Let’s look for observations for all oak trees. We can use filter where the <code>common_name</code> is ‘oaks’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>oaks_obs <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'oaks'</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(oaks_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 218  37</code></pre>
</div>
</div>
<p>We have 218 observations. However, when we used the iNaturalist site to look for ‘oaks’ for ‘Los Angeles City Nature Challenge Cumulative Observations 2016-2024’, we get <a href="https://www.inaturalist.org/observations?project_id=los-angeles-city-nature-challenge-cumulative-observations-2016-2024&amp;subview=map&amp;taxon_id=47851&amp;verifiable=any">1369 observations</a>. What’s causing the difference?</p>
<p>When you search for ‘oaks’ on iNaturalist, click the ‘About’ link, and it will bring you to the <a href="https://www.inaturalist.org/taxa/47851-Quercus">taxa page for ‘oaks’</a>.</p>
<p><img src="images/search_oaks.png" class="img-fluid"></p>
<p><img src="images/oaks_taxa.png" class="img-fluid" alt="oaks taxa page"></p>
<p>‘Oaks’ is the common name for genus Quercus. When you search iNaturalist observations for ‘oaks’, iNaturalist returns observations that belong to the genus Quercus, which includes species such as ‘Live Coast Oak’ and ‘Valley Oak’. Our query <code>common_name == 'oaks'</code> only looked for observations that are ‘oaks’; it ignored observations that are oak species. To match the iNaturalist search results, we need to look for all observations where the genus equals Quercus.</p>
<p>We can use <code>names()</code> to get all the taxon name fields.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(inat_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "id"                         "observed_on"               
 [3] "time_observed_at"           "user_id"                   
 [5] "user_login"                 "user_name"                 
 [7] "created_at"                 "updated_at"                
 [9] "quality_grade"              "license"                   
[11] "url"                        "image_url"                 
[13] "sound_url"                  "tag_list"                  
[15] "description"                "captive_cultivated"        
[17] "latitude"                   "longitude"                 
[19] "positional_accuracy"        "public_positional_accuracy"
[21] "geoprivacy"                 "taxon_geoprivacy"          
[23] "coordinates_obscured"       "scientific_name"           
[25] "common_name"                "iconic_taxon_name"         
[27] "taxon_id"                   "taxon_kingdom_name"        
[29] "taxon_phylum_name"          "taxon_class_name"          
[31] "taxon_order_name"           "taxon_family_name"         
[33] "taxon_genus_name"           "taxon_species_name"        
[35] "taxon_subspecies_name"      "threatened"                
[37] "establishment_means"       </code></pre>
</div>
</div>
<p>The ‘Taxonomy’ tab on iNaturalist taxa pages show the taxonomic hierarchy with all the taxon ranks.</p>
<p><img src="images/oaks_taxonomy.png" class="img-fluid"></p>
<p>We can create a filter command to represent the taxonomic hierarchy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>oaks_obs_fixed <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    taxon_kingdom_name <span class="sc">==</span> <span class="st">'Plantae'</span> <span class="sc">&amp;</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    taxon_phylum_name <span class="sc">==</span> <span class="st">'Tracheophyta'</span> <span class="sc">&amp;</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    taxon_class_name <span class="sc">==</span> <span class="st">'Magnoliopsida'</span> <span class="sc">&amp;</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>    taxon_order_name <span class="sc">==</span> <span class="st">'Fagales'</span> <span class="sc">&amp;</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    taxon_family_name <span class="sc">==</span> <span class="st">'Fagaceae'</span> <span class="sc">&amp;</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>    taxon_genus_name <span class="sc">==</span> <span class="st">'Quercus'</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The reason why I listed the hierarchy instead of just filtering by <code>taxon_genus_name == 'Quercus'</code> is because of limitations of my knowledge and the limitations of the information provided by the CSV. Some Latin words are used multiple times to represent different taxa. For instance Eisenia is a genus for a type of worm and a genus for a type kelp. A filter command for <code>taxon_genus_name == 'Eisenia'</code> would return observations for two very different organisms. I don’t have enough expertise to know if a taxa name is unique, so I list the hierarchy. Someone with more expertise might know there is only one Quercus in Plantae, and use <code>filter(taxon_kingdom_name == 'Plantae' &amp; taxon_genus_name == 'Quercus')</code>.</p>
<p>iNaturalist gives each taxa name a unique id. Worm Eisenia is 128842, kelp Eisenia is 125880, and Quercus is 47851. When iNaturalist searches for observations for a given taxa, it uses the unique id for the search to avoid the problem of dupicate names. Unfortunately the the CSV does not provide ids for each taxon rank, so we can’t do a search by id.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(oaks_obs_fixed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1367   37</code></pre>
</div>
</div>
<p>We now get 1367 observations.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The reason why iNaturalist has 1369 observations for ‘oaks’ but we have 1367 is because iNaturalist has two ‘oaks’ observations which don’t have latitude and longitude data. Our cleaned iNaturalist data excludes observations without latitude and longitude.</p>
</div>
</div>
<p>Let’s examine the number of observations for each type of oak. We can use <code>count()</code> to get the counts, and <code>View()</code> to see the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>oaks_count <span class="ot">&lt;-</span> oaks_obs_fixed <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name) <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>oaks_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 34 × 3
   common_name          scientific_name            n
   &lt;chr&gt;                &lt;chr&gt;                  &lt;int&gt;
 1 coast live oak       Quercus agrifolia        711
 2 oaks                 Quercus                  218
 3 valley oak           Quercus lobata           113
 4 California scrub oak Quercus berberidifolia    74
 5 canyon live oak      Quercus chrysolepis       55
 6 Tucker's Oak         Quercus john-tuckeri      25
 7 high-latitude oaks   Quercus                   20
 8 Engelmann oak        Quercus engelmannii       17
 9 &lt;NA&gt;                 Dumosae                   16
10 cork oak             Quercus suber             12
# ℹ 24 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(oaks_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While most of the observations are species (as evidence by the two part name), there are 218 observations that could only be identified to the genus Quercus.</p>
<p>Another example, let’s search for ‘trees’. When we search iNaturalist for ‘trees’, the first result is <a href="https://www.inaturalist.org/taxa/211194-Tracheophyta">Phylum Tracheophyta</a>. Let’s look at our data using <code>taxon_phylum_name</code> and ‘Tracheophyta’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>trees_obs <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(taxon_kingdom_name <span class="sc">==</span> <span class="st">'Plantae'</span> <span class="sc">&amp;</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>           taxon_phylum_name <span class="sc">==</span> <span class="st">'Tracheophyta'</span>)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(trees_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 95372    37</code></pre>
</div>
</div>
<p>There are 95372 Tracheophyta observations.</p>
<p>Let’s get a count of observations for Tracheophyta.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>trees_count <span class="ot">&lt;-</span> trees_obs <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name) <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>trees_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,759 × 2
   common_name                n
   &lt;chr&gt;                  &lt;int&gt;
 1 &lt;NA&gt;                    2433
 2 dicots                  2013
 3 flowering plants        1161
 4 California poppy         934
 5 California brittlebush   842
 6 black sage               796
 7 California sagebrush     794
 8 California Buckwheat     751
 9 coast live oak           711
10 grasses                  673
# ℹ 3,749 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(trees_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We are getting plants such as California poppy, grasses, which aren’t trees. Why is that?</p>
<p>If we look up <a href="https://en.wikipedia.org/wiki/Vascular_plant">‘Tracheophyta’ in Wikipedia</a>:</p>
<blockquote class="blockquote">
<p>The group includes most land plants (c. 300,000 accepted known species) other than mosses.</p>
</blockquote>
<p>If we look up <a href="https://en.wikipedia.org/wiki/Tree">‘tree’ in Wikipedia</a>:</p>
<blockquote class="blockquote">
<p>Trees are not a monophyletic taxonomic group but consist of a wide variety of plant species that have independently evolved a trunk and branches as a way to tower above other plants to compete for sunlight. The majority of tree species are angiosperms or hardwoods; of the rest, many are gymnosperms or softwoods.</p>
</blockquote>
<blockquote class="blockquote">
<p>Although “tree” is a common word, there is no universally recognised precise definition of what a tree is, either botanically or in common language.</p>
</blockquote>
<p>In other words, there is no one word we can use to find all trees. The fact that iNaturalist shows Tracheophyta as the first search result for ‘trees’ is a little quirk with the iNaturalist search algorithm. To find all trees, we would need to get a list of trees names, and create a filter command with all the tree names.</p>
<p>When looking for a group of related organisms using higher taxanomy, it might take some trial and error to get the results you want.</p>
</section>
<section id="exercise-2" class="level2 exercise">
<h2 class="anchored" data-anchor-id="exercise-2">Exercise 2</h2>
<p>Get all your CNC observations that are research grade</p>
<ul>
<li>Use <code>select()</code>, <code>filter()</code>, <code>&amp;</code></li>
<li>The results should have <code>user_login</code> equal to your iNaturalist username</li>
<li>The results should have <code>quality_grade</code> equal to research.</li>
<li>The results should have <code>user_login</code>, <code>observed_on</code>, <code>common_name</code>, <code>scientific_name</code> columns</li>
<li>save the results to <code>my_obs_2</code> object</li>
</ul>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>my_obs_2 <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span> <span class="sc">&amp;</span> quality_grade <span class="sc">==</span> <span class="st">'research'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name, scientific_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="exercise-3" class="level2 exercise">
<h2 class="anchored" data-anchor-id="exercise-3">Exercise 3</h2>
<p>Get all your observations for two species</p>
<ul>
<li>Use <code>select()</code>, <code>filter()</code> , <code>|</code></li>
<li>use <code>unique()</code> to see all common names from <code>my_obs</code></li>
<li>The results should have <code>user_login</code> equal to your iNaturalist username</li>
<li>The results should have <code>common_name</code> equal to two species</li>
<li>The results should have <code>user_login</code>, <code>observed_on</code>, <code>common_name</code>, <code>scientific_name</code> columns</li>
<li>save the results to <code>my_obs_3</code> object</li>
</ul>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_obs<span class="sc">$</span>common_name)[<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Red-eared Slider"       "Monarch"                "San Diego Gopher Snake"
 [4] "California Towhee"      "Cooper's Hawk"          "tropical milkweed"     
 [7] "Allen's Hummingbird"    "Northern Mockingbird"   "House Sparrow"         
[10] "Indian Peafowl"        </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>my_obs_3 <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(common_name <span class="sc">==</span> <span class="st">'Red-eared Slider'</span> <span class="sc">|</span> common_name<span class="sc">==</span><span class="st">'Monarch'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name, scientific_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="add-new-columns-with-mutate" class="level2">
<h2 class="anchored" data-anchor-id="add-new-columns-with-mutate">Add new columns with mutate()</h2>
<p>Another common task is creating a new column based on values in existing columns. For example, we could add a new column for year.</p>
<p>Use <code>mutate()</code> from <strong>dplry</strong> to add a column. We pass in the name of the new column, and the value of the column.</p>
<p>Use <code>year()</code> from <strong>lubridate</strong> on a date column to get the year.</p>
<p>Let’s get <code>observed_on</code> for rows 10315 to 10325</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>(inat_data<span class="sc">$</span>observed_on)[<span class="dv">10315</span><span class="sc">:</span><span class="dv">10325</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "2016-04-15" "2016-04-15" "2016-04-18" "2016-04-16" "2017-04-14"
 [6] "2017-04-15" "2017-04-14" "2017-04-14" "2017-04-14" "2017-04-14"
[11] "2017-04-14"</code></pre>
</div>
</div>
<p>Let’s get use <code>year()</code> to get the year from <code>observed_on</code> for rows 10315 to 10325</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">year</span>(inat_data<span class="sc">$</span>observed_on)[<span class="dv">10315</span><span class="sc">:</span><span class="dv">10325</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2016 2016 2016 2016 2017 2017 2017 2017 2017 2017 2017</code></pre>
</div>
</div>
<p>This code will add <code>year</code> column using the <code>year(observed_on)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can click on <code>temp</code> in <strong>Environment</strong> tab to see the data frame with <code>year</code> column.</p>
<p>We can also use <code>table()</code> to get the number of observations per year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(temp<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 2016  2017  2018  2019  2020  2021  2022  2023  2024 
10392 17495 19164 34057 19524 22549 19597 26602 22258 </code></pre>
</div>
</div>
<p>Let’s get all observations for 2020. We use mutate to add year column, and use filter to select rows where year is 2020.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on)) <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2020</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19,524 × 38
         id observed_on time_observed_at user_id user_login user_name created_at
      &lt;dbl&gt; &lt;date&gt;      &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;     
 1 43036512 2020-04-24  2020-04-24 07:0…  907908 samatha    &lt;NA&gt;      2020-04-2…
 2 43036525 2020-04-24  2020-04-24 07:0… 2556338 charlesja… Charles … 2020-04-2…
 3 43036534 2020-04-24  2020-04-24 07:0…  146517 maiz       &lt;NA&gt;      2020-04-2…
 4 43036755 2020-04-24  2020-04-24 07:0… 2556338 charlesja… Charles … 2020-04-2…
 5 43036856 2020-04-24  2020-04-24 07:0… 2556338 charlesja… Charles … 2020-04-2…
 6 43036989 2020-04-24  2020-04-24 07:0…   74669 amyjaecke… Amy Jaec… 2020-04-2…
 7 43037041 2020-04-24  2020-04-24 07:0…   74669 amyjaecke… Amy Jaec… 2020-04-2…
 8 43037308 2020-04-24  2020-04-24 07:1… 2556338 charlesja… Charles … 2020-04-2…
 9 43037581 2020-04-24  2020-04-24 07:1… 2556338 charlesja… Charles … 2020-04-2…
10 43037631 2020-04-24  2020-04-24 07:1…  403949 jaeckerb   &lt;NA&gt;      2020-04-2…
# ℹ 19,514 more rows
# ℹ 31 more variables: updated_at &lt;chr&gt;, quality_grade &lt;chr&gt;, license &lt;chr&gt;,
#   url &lt;chr&gt;, image_url &lt;chr&gt;, sound_url &lt;chr&gt;, tag_list &lt;chr&gt;,
#   description &lt;chr&gt;, captive_cultivated &lt;lgl&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, positional_accuracy &lt;dbl&gt;,
#   public_positional_accuracy &lt;dbl&gt;, geoprivacy &lt;chr&gt;, taxon_geoprivacy &lt;chr&gt;,
#   coordinates_obscured &lt;lgl&gt;, scientific_name &lt;chr&gt;, common_name &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="exercise-4" class="level2 exercise">
<h2 class="anchored" data-anchor-id="exercise-4">Exercise 4</h2>
<p>Get all of your observations from last year.</p>
<ul>
<li>Use <code>select()</code> and <code>filter()</code></li>
<li>Use <code>mutate()</code> and <code>year()</code> to add year column</li>
<li>The results should have <code>user_login</code> equal to your iNaturalist username</li>
<li>The results should have <code>year</code> equal last year</li>
<li>The results should have <code>user_login</code>, <code>observed_on</code>, <code>common-name</code>, <code>scientific_name</code>.</li>
</ul>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on)) <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span> <span class="sc">&amp;</span> year <span class="sc">==</span> <span class="dv">2024</span>) <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(user_login, observed_on, common_name, scientific_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  user_login observed_on common_name                scientific_name             
  &lt;chr&gt;      &lt;date&gt;      &lt;chr&gt;                      &lt;chr&gt;                       
1 natureinla 2024-04-29  San Diego Alligator Lizard Elgaria multicarinata webbii</code></pre>
</div>
</div>
</div>
</section>
<section id="count-the-number-of-rows-with-count" class="level2">
<h2 class="anchored" data-anchor-id="count-the-number-of-rows-with-count">Count the number of rows with count()</h2>
<p>Use <code>count()</code> from <strong>dplyr</strong> to count the number of values for one or more columns. We pass in the column names as arguments to <code>count()</code></p>
<p>Let’s try counting of all observations by year. Use <code>mutate()</code> to add a year column. Use <code>count()</code> to count the number of observations for each year. By default, count will add a new column caled <code>n</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on)) <span class="sc">%&gt;%</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
   year     n
  &lt;dbl&gt; &lt;int&gt;
1  2016 10392
2  2017 17495
3  2018 19164
4  2019 34057
5  2020 19524
6  2021 22549
7  2022 19597
8  2023 26602
9  2024 22258</code></pre>
</div>
</div>
<p>We can specify the name of the count column by passing in <code>name</code> argument to <code>count()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on)) <span class="sc">%&gt;%</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year, <span class="at">name=</span><span class="st">'obs_count'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
   year obs_count
  &lt;dbl&gt;     &lt;int&gt;
1  2016     10392
2  2017     17495
3  2018     19164
4  2019     34057
5  2020     19524
6  2021     22549
7  2022     19597
8  2023     26602
9  2024     22258</code></pre>
</div>
</div>
<p>Let’s count the number of observations for each species. We will pass in both ‘common_name’ and ‘scientific_name’ because some species don’t have a common_name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name, <span class="at">name=</span><span class="st">'obs_count'</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,865 × 3
   common_name                             scientific_name        obs_count
   &lt;chr&gt;                                   &lt;chr&gt;                      &lt;int&gt;
 1 Abalone                                 Haliotis                       7
 2 Abbott's bushmallow                     Malacothamnus abbottii         1
 3 Abelias                                 Abelia                         1
 4 Abert's Thread-waisted Wasp             Ammophila aberti               3
 5 Abyssinian banana                       Ensete ventricosum             1
 6 Acacia Psyllid                          Acizzia uncatoides             2
 7 Acacias, Mimosas, mesquites, and allies Mimosoideae                   10
 8 Acalyptrate Flies                       Acalyptratae                  66
 9 Acanthus                                Acanthus                      23
10 Achilid Planthoppers                    Achilidae                      1
# ℹ 9,855 more rows</code></pre>
</div>
</div>
<p>It’s often useful to take a look at the results in some order, like the lowest count to highest. We can use the <code>arrange()</code> function from <strong>dplyr</strong> for that. We pass in the columns we want to order by to <code>arrange()</code>. By default, <code>arrange()</code> will return values from lowest to highest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name, <span class="at">name=</span><span class="st">'obs_count'</span>)   <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(obs_count)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,865 × 3
   common_name                     scientific_name         obs_count
   &lt;chr&gt;                           &lt;chr&gt;                       &lt;int&gt;
 1 Abbott's bushmallow             Malacothamnus abbottii          1
 2 Abelias                         Abelia                          1
 3 Abyssinian banana               Ensete ventricosum              1
 4 Achilid Planthoppers            Achilidae                       1
 5 Acorn Moth                      Blastobasis glandulella         1
 6 Acotylean Flatworms             Acotylea                        1
 7 Active Free-living Bristleworms Errantia                        1
 8 Afghan Tortoise                 Testudo horsfieldii             1
 9 African Clawed Frog             Xenopus laevis                  1
10 African Milk Weed               Euphorbia trigona               1
# ℹ 9,855 more rows</code></pre>
</div>
</div>
<p>If we want to reverse the order, we can wrap the column names in <code>desc()</code> from <strong>dplyr</strong>. This will return values from highest to lowest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name, <span class="at">name=</span><span class="st">'obs_count'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(obs_count))</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,865 × 3
   common_name            scientific_name          obs_count
   &lt;chr&gt;                  &lt;chr&gt;                        &lt;int&gt;
 1 Western Fence Lizard   Sceloporus occidentalis       3339
 2 Western Honey Bee      Apis mellifera                2060
 3 dicots                 Magnoliopsida                 2013
 4 plants                 Plantae                       1712
 5 Eastern Fox Squirrel   Sciurus niger                 1475
 6 House Finch            Haemorhous mexicanus          1263
 7 Mourning Dove          Zenaida macroura              1205
 8 flowering plants       Angiospermae                  1161
 9 California poppy       Eschscholzia californica       934
10 Convergent Lady Beetle Hippodamia convergens          929
# ℹ 9,855 more rows</code></pre>
</div>
</div>
<p>use <code>slice()</code> from <strong>dplyr</strong> to return only certain number of records. <code>slice(start:end)</code> will return rows from the starting number to the ending number.</p>
<p>Let’s get the top ten species with the most observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name, <span class="at">name=</span><span class="st">'obs_count'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(obs_count))  <span class="sc">%&gt;%</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   common_name            scientific_name          obs_count
   &lt;chr&gt;                  &lt;chr&gt;                        &lt;int&gt;
 1 Western Fence Lizard   Sceloporus occidentalis       3339
 2 Western Honey Bee      Apis mellifera                2060
 3 dicots                 Magnoliopsida                 2013
 4 plants                 Plantae                       1712
 5 Eastern Fox Squirrel   Sciurus niger                 1475
 6 House Finch            Haemorhous mexicanus          1263
 7 Mourning Dove          Zenaida macroura              1205
 8 flowering plants       Angiospermae                  1161
 9 California poppy       Eschscholzia californica       934
10 Convergent Lady Beetle Hippodamia convergens          929</code></pre>
</div>
</div>
</section>
<section id="exercise-5" class="level2 exercise">
<h2 class="anchored" data-anchor-id="exercise-5">Exercise 5</h2>
<p>Get the number of observation you made per year</p>
<ul>
<li>Use <code>mutate()</code> and <code>year()</code> to add year column</li>
<li>Use <code>count() to count the number of observations</code></li>
<li>Use <code>filter()</code> to select your observations</li>
</ul>
<div class="answer">
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>inat_data <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(observed_on)) <span class="sc">%&gt;%</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(user_login <span class="sc">==</span> <span class="st">'natureinla'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year, <span class="at">name=</span><span class="st">'obs_count'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
   year obs_count
  &lt;dbl&gt;     &lt;int&gt;
1  2016       930
2  2017      1055
3  2018       599
4  2019       350
5  2020        10
6  2021         2
7  2023         9
8  2024         1</code></pre>
</div>
</div>
</div>
</section>
<section id="save-data" class="level2">
<h2 class="anchored" data-anchor-id="save-data">Save data</h2>
<p>If you want to save your results, you can save the data frames as CSVs. First, assign the data frame to an object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>top_ten <span class="ot">&lt;-</span> inat_data <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(common_name, scientific_name, <span class="at">name=</span><span class="st">'obs_count'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(obs_count))  <span class="sc">%&gt;%</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>top_ten</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   common_name            scientific_name          obs_count
   &lt;chr&gt;                  &lt;chr&gt;                        &lt;int&gt;
 1 Western Fence Lizard   Sceloporus occidentalis       3339
 2 Western Honey Bee      Apis mellifera                2060
 3 dicots                 Magnoliopsida                 2013
 4 plants                 Plantae                       1712
 5 Eastern Fox Squirrel   Sciurus niger                 1475
 6 House Finch            Haemorhous mexicanus          1263
 7 Mourning Dove          Zenaida macroura              1205
 8 flowering plants       Angiospermae                  1161
 9 California poppy       Eschscholzia californica       934
10 Convergent Lady Beetle Hippodamia convergens          929</code></pre>
</div>
</div>
<p>Then <code>write_csv()</code> from <strong>dplyr</strong> to create a CSV. The first argument is the data frame to save. The second argument is the relative path of where to save the file. To keep our files organized, we are saving CSVs to the results folder. You should give the file a sensible name to help you remember what is in the file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(top_ten, <span class="st">'results/top_ten_observations.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>