---
title: "Science and Coding concepts"
format: html
---

## Biology Concepts

### Urban Ecology

More content needed...

### Taxonomy

Wikipedia description of [taxonomy](https://en.wikipedia.org/wiki/Taxonomy_(biology))

> In biology, taxonomy (from Ancient Greek τάξις (taxis) 'arrangement' and -νομία (-nomia) 'method') is the scientific study of naming, defining (circumscribing) and classifying groups of biological organisms based on shared characteristics. Organisms are grouped into taxa (singular: taxon) and these groups are given a taxonomic rank; groups of a given rank can be aggregated to form a more inclusive group of higher rank, thus creating a taxonomic hierarchy. The principal ranks in modern use are domain, kingdom, phylum (division is sometimes used in botany in place of phylum), class, order, family, genus, and species.

The current system of taxonomy uses Latin names for the scientific name. Each scientific name can have multiple common names in multiple languages.

Here's iNaturalist taxonomy for Western Fence Lizard, the most common species in Los Angeles City Nature Challenge.

**Rank**: Latin scientific name (English common name)

-   **Kingdom**: Animalia (Animals)

-   **Phylum**: Chordata (Chordates)

-   **Class**: Reptilia (Reptiles)

-   **Order**: Squamata (Snakes and Lizards)

-   **Family**: Phrynosomatidae (Phrynosomatid Lizards)

-   **Genus**: Sceloporus (Spiny Lizards)

-   **Species**: Sceloporus occidentalis (Western Fence Lizard)

In theory, every iNaturalist observation represents a species. In practice, an iNaturalist observation will be assigned to a particular taxa name and taxon rank based on the qualitity of the recorded data, the expertise of the observer, the suggestion algorithms of iNaturalist, and the expertise of people who help identify observations.

## Coding Concepts

The basis of programming is that we write down instructions for the computer to follow, and then we tell the computer to follow those instructions. We write these instructions in the form of *code*, which is a common language that is understood by the computer and humans (after some practice). We call these instructions *commands*, and we tell the computer to follow the instructions by *running* (also called *executing*) the commands.

## Geographic concepts

Geospatial data is data that has a location.

There are various file formats for geographic data. Shape files for GIS applications, KML for Google maps, geojson for web applications.

### **Coordinate Reference Systems**

Earth is a 3D sphere. Maps are 2D representation of a 3D sphere. Map projections are ways to represent a spherical Earth as a flat surface.

Geospatial data should have a coordinate reference system (CRS) that defines how the two-dimensional, projected map relates to real places on the earth. A CRS also tells the mapping software what method should be used to flatten or project the data in geographic space. Data from the same location but saved in different projections will not line up in any mapping software. Thus, it’s important when working with spatial data to identify the coordinate reference system applied to the data and retain it throughout data processing and analysis.
