---
title: "Next steps"
format: html
editor: visual
time: 5 minutes
---

We have covered various ways to do basic analyze iNaturalist data. Next step is for you to come up with some questions, and analyze the CNC iNaturalist data.

## Developing your analysis

1.  Come up with one or more questions that you are interested in.
2.  Review the online lessons notes and use Codespace to run the lesson-scripts.
3.  We did one exercise in class. Optionally, do the rest of the exercises in the ["Working with data"](working-with-data.qmd), ["Creating maps"](creating-maps.qmd), and ["Creating charts"](creating-charts.qmd) sections to get more practice with coding. Click in "Show solution" button on the online lesson to see the solution.
4.  Figure out how to go from 191K City Nature Challenge observations to the observation you want. If you want to study one or more species, review the examples that filter by species. If you want to study a group of species, review the higher taxa examples. If you want to limit the observations to a particular location, review the examples that show filtering observations using a geographic boundaries. If you want to study your own observations, review the examples about filtering by iNaturalist user. If you want to mimic the data standards used by scientists, review the examples about filter by research grade and licenses. If you want to limit the observations by year, review the examples about filtering by years. If you want to remove some of the biases in community science data, review normalizing iNaturalist data examples.
5.  Read the ["Restart Codespace"](https://wykhuh.github.io/after-inaturalist-r/lessons/setup.html#restart-codespace) section to restart Codespace. Read the ["Stop Codespace"](https://wykhuh.github.io/after-inaturalist-r/lessons/setup.html#stop-codespace) section to learn how to stop Codespace at the end of your work session.
6.  Create a script file to save your work.
7.  Copy and paste examples provided in the lessons, and adjust them to fit your needs. When you have something that kinda works, save the script file and the results. Save your scripts often since RStudio does not have auto save functionality. Save the scripts to the scripts folder. Save any CSVs and images you generate to the results folder.
8.  Data exploration is an iterative process. Chances are, you won't get your final results on your first day. Try different way to look at the data. Use `filter()`, `select()`, `count()`, and `mutate()` to change the data. Then create summary tables, charts, and/or maps to find patterns. Repeat the process. You can create multiple script files.
9.  As you are analyzing the data, think about how you want to present your results. Your presentation should represent your analysis, your voice, and your interests. 
10. Attend the office hours or email me if you have questions.
